### ISSUE TITLE
Compiling fails at finding `../../../lib/linux-x86_64/libseq.a`

### ISSUE THREAD

**Issue by codedump** [epics-modules/asyn#154]
Hello,

I'm failing with current HEAD at this:
```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_ -DUNIX  -Dlinux      -O3 -g   -Wall      -mtune=generic     -m64  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include          -I/opt/epics/base/include/compiler/gcc -I/opt/epics/base/include/os/Linux -I/opt/epics/base/include        -MM -MF testEpics_registerRecordDeviceDriver.d  testEpics_registerRecordDeviceDriver.cpp
Installing created dbd file ../../../dbd/testEpics.dbd
/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_ -DUNIX  -Dlinux      -O3 -g   -Wall -Werror-implicit-function-declaration      -mtune=generic     -m64  -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include          -I/opt/epics/base/include/compiler/gcc -I/opt/epics/base/include/os/Linux -I/opt/epics/base/include        -c ../int32Driver.c
/usr/bin/gcc  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_ -DUNIX  -Dlinux      -O3 -g   -Wall -Werror-implicit-function-declaration      -mtune=generic     -m64  -fPIC -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include          -I/opt/epics/base/include/compiler/gcc -I/opt/epics/base/include/os/Linux -I/opt/epics/base/include        -c ../uint32DigitalDriver.c
make[3]: *** No rule to make target '../../../lib/linux-x86_64/libseq.a', needed by 'libtestEpicsSupport.a'.  Stop.
make[3]: Leaving directory '/tmp/asyn/testEpicsApp/src/O.linux-x86_64'
make[2]: *** [/opt/epics/base/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[2]: Leaving directory '/tmp/asyn/testEpicsApp/src'
make[1]: *** [/opt/epics/base/configure/RULES_DIRS:85: src.install] Error 2
make[1]: Leaving directory '/tmp/asyn/testEpicsApp'
make: *** [/opt/epics/base/configure/RULES_DIRS:85: testEpicsApp.install] Error 2
```

I've also tried disabling `SNCSEC` in `configure/RELEASE` to no avail.

For reference, I prepared the source as described in [issue 151](https://github.com/epics-modules/asyn/issues/151):
```
$ git clone --recurse-submodules https://github.com/epics-modules/asyn.git
$ cd async
$ cp configure/RELEASE RELEASE.orig
$ cp configure/CONFIG_SITE CONFIG_SITE.orig
$ cat RELEASE.orig     \
    | sed "s|SUPPORT=/corvette/home/epics|SUPPORT=/opt/epics/support|g"     \
    | sed "s|EPICS_BASE=\(.*\)|EPICS_BASE=/opt/epics/base|g" \
    > configure/RELEASE
$ cat CONFIG_SITE.orig \
    | sed "s|^\(.*\)TIRPC=\(.*\)$|TIRPC=YES|g" \
    > configure/CONFIG_SITE

$ make
...
```

Epics-base is installed in `/opt/epics/base` from today's HEAD.

Am I missing something?

**Comment by tboegi** [comment]
See testEpicsApp/src/Makefile:50:ifdef SNCSEQ

I suspect that the same ifdef is missing here:
testIPServerApp/src/Makefile

**Comment by MarkRivers** [comment]
@codedump I don't understand this.  Your build is failing in testEpicsApp.  But testEpicsApp/src/Makefile correctly only uses libseq when building libtestEpicsSupport if SNCSEQ is defined in configure/RELEASE.
https://github.com/epics-modules/asyn/blob/45d4679b0a0bb405aacf928013d0982247067b52/testEpicsApp/src/Makefile#L29

You said you disabled SNCSEQ in configure/RELEASE and that did not help.  That does not make sense.  I just tested building testEpicsApps with SNCSEQ commented out in configure/RELEASE and it worked fine.  Note that it is not linking with seq.  I have added line breaks for clarity.

```
/usr/bin/g++ -o libtestEpicsSupport.so -shared -fPIC -Wl,-hlibtestEpicsSupport.so 
-L/home/epics/devel/asyn-4-42/lib/linux-x86_64 
-L/home/epics/devel/calc-3-7-3/lib/linux-x86_64 
-L/home/epics/devel/sscan-2-11-3/lib/linux-x86_64 
-L/usr/local/epics-devel/base-7.0.5/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/asyn-4-42/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/calc-3-7-3/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/sscan-2-11-3/lib/linux-x86_64 
-Wl,-rpath,/usr/local/epics-devel/base-7.0.5/lib/linux-x86_64           
-rdynamic -m64         int32Driver.o uint32DigitalDriver.o    
-lasyn -lcalc -lsscan -ldbRecStd -ldbCore -lca -lCom   -lpthread   -lreadline -lm -lrt -ldl -lgcc
Installing shared library ../../../lib/linux-x86_64/libtestEpicsSupport.so
Installing library ../../../lib/linux-x86_64/libtestEpicsSupport.a
```
This is what I see if SNCSEQ is not commented out in configure/RELEASE. Note that it is linking with seq.
```
/usr/bin/g++ -o libtestEpicsSupport.so -shared -fPIC -Wl,-hlibtestEpicsSupport.so 
-L/home/epics/devel/asyn-4-42/lib/linux-x86_64 
-L/home/epics/devel/calc-3-7-3/lib/linux-x86_64 
-L/home/epics/devel/seq-2-2-5/lib/linux-x86_64 
-L/home/epics/devel/sscan-2-11-3/lib/linux-x86_64 
-L/usr/local/epics-devel/base-7.0.5/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/asyn-4-42/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/calc-3-7-3/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/seq-2-2-5/lib/linux-x86_64 
-Wl,-rpath,/home/epics/devel/sscan-2-11-3/lib/linux-x86_64 
-Wl,-rpath,/usr/local/epics-devel/base-7.0.5/lib/linux-x86_64           
-rdynamic -m64         int32Driver.o uint32DigitalDriver.o    
-lasyn -lcalc -lsscan -lseq -lpv -ldbRecStd -ldbCore -lca -lCom   -lpthread   -lreadline -lm -lrt -ldl -lgcc
Installing shared library ../../../lib/linux-x86_64/libtestEpicsSupport.so
Installing library ../../../lib/linux-x86_64/libtestEpicsSupport.a
```

**Comment by MarkRivers** [comment]
@tboegi said:
>See testEpicsApp/src/Makefile:50:ifdef SNCSEQ
I suspect that the same ifdef is missing here:
testIPServerApp/src/Makefile

That is not an error because testIPServerApp is only built if SNCSEQ is defined.  That is done in this code in asyn/Makefile.
```
  ifdef SNCSEQ
    DIRS += testIPServerApp
    testIPServerApp_DEPEND_DIRS = asyn
    iocBoot_DEPEND_DIRS += testIPServerApp
  endif
```
If you went into testIPServerApp and ran make at that level you would get an error, but when running make at the top level it will never enter that directory.

I just built all of asyn with SNCSEQ commented out in asyn/configure/RELEASE and it built fine.

**Comment by MarkRivers** [comment]
> I've also tried disabling SNCSEC in configure/RELEASE to no avail.

Did you do "make clean" after doing that?  I think that is needed because otherwise the .depends file will still think libseq is needed.

**Comment by MarkRivers** [comment]
The answer is that asyn by default depends on SNCSEQ.  You can install it from here: 
https://www-csr.bessy.de/control/SoftDist/sequencer/Installation.html

If you don't want to use it then you can comment it out in configure/RELEASE.

In the script you list above you did not comment out SNCSEQ in configure/RELEASE.  If you had I believe you would not have an error.

**Comment by MarkRivers** [comment]
> One other small confusion on the side that I have is: what is SNCSEQ, 

SNCSEQ is a state notation language compiler for EPICS.  You can find it easily with Google.
https://www-csr.bessy.de/control/SoftDist/sequencer/Manual.html

> and do I have to somehow install it manually? 

If you want to use it with asyn then you do need to install it manually.  The above link shows how to download it.  The RELEASE file correctly states that it is only required for testIPServer, which is a test application.

> I'd have expected it to be installed "by default" with Epics-Base; 

It is not part of EPICS base, it is an optional module.

> or I'd have expected the Asyn documentation to point me to the necessity of installing it.

It is not necessary, but because it is used by default you are right it should be documented.  

I have just improved asyn/configure/RELEASE to document where to obtain all of the modules that it depends on:
https://github.com/epics-modules/asyn/blob/master/configure/RELEASE
```
#RELEASE Location of external products

SUPPORT=/corvette/home/epics/devel

# IPAC is only necessary if support for Greensprings IP488 is required
# IPAC release V2-7 or later is required.
# It can be obtained here: https://github.com/epics-modules/ipac
IPAC=$(SUPPORT)/ipac-2-15

# SEQ is required for testIPServer
# It can be obtained here: https://www-csr.bessy.de/control/SoftDist/sequencer/Manual.html
SNCSEQ=$(SUPPORT)/seq-2-2-5

# For sCalcout support in asynOctet - applications include asynCalc.dbd
# It can be obtained here: https://github.com/epics-modules/calc
CALC=$(SUPPORT)/calc-3-7-3

# If CALC was built with SSCAN support then SSCAN must be defined for testEpicsApp
# It can be obtained here: https://github.com/epics-modules/sscan
SSCAN=$(SUPPORT)/sscan-2-11-3

#  EPICS_BASE 3.14.6 or later is required
#  It can be obtained here: https://github.com/epics-base/epics-base
EPICS_BASE=/corvette/usr/local/epics-devel/base-7.0.5

-include $(TOP)/../RELEASE.local
-include $(TOP)/../RELEASE.$(EPICS_HOST_ARCH).local
-include $(TOP)/configure/RELEASE.local
```

**Comment by codedump** [comment]
@MarkRivers

Yes, now it works. I don't know what my mistake was, but it must have been on my part (maybe among all the `make` and `make clean` I still forgot the decisive one after all.)

Anyway, would you take a PR to the README or the installation guide to document this behavior? I believe that either the dependency on SNCSEQ, or the necessity to comment it out in `configure/RELEASE`, needs to be prominently documented whereever the install guide is documented. I'm currently building after [this](https://epics.anl.gov/modules/soft/asyn/) -- if you kindly point me toward the path of the file, which I can't seem to find in the `documentation` folder, I'll be happy to include this piece of information.

**Comment by MarkRivers** [comment]
I'd be happy to accept a PR.  

The link you gave above (https://epics.anl.gov/modules/soft/asyn/) is obsolete.  

On the main Github page for asyn (https://github.com/epics-modules/asyn) it points to https://epics-modules.github.io/master/asyn/ as the asyn home page, which is the new location.  The epics.anl.gov page should be changed to redirect to that.

Note that anyone who installs asyn does need to manually edit configure/RELEASE.  That file does now document what all dependencies are required for, and where to find them.

**Comment by anjohnson** [comment]
Redirect installed on the old [epics.anl.gov Asyn index](https://epics.anl.gov/modules/soft/asyn/) page (my pointers had already been changed). I'd have to ask IT for help if you wanted redirection of the files in all of the old versions, which Google almost certainly knows about, or I could just delete them all.

**Comment by MarkRivers** [comment]
@anjohnson thanks.  I think the redirect on the index page is sufficient.  That was the first result for a Google search of "epics asyn".
