### ISSUE TITLE
devAsynInt64Array support missing

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-modules/asyn#195]
There is a devAsynInt64Array.dbd which gets installed, and a devAsynInt64Array.c file, but it is never compiled.
However, simply adding it to asyn/Makefile makes the build fail: fatal error: devAsynXXXArray.h: No such file or directory

**Comment by dirk-zimoch** [comment]
False alarm, the devAsynInt64Array is in devAsynXXXArray.cpp.

Instead: The file devAsynInt64Array.c is probably a leftover ans should be removed.

**Comment by MarkRivers** [comment]
Thanks for catching that, I have deleted devAsynInt64Array.c.
