### ISSUE TITLE
Invalid baudrate error handling

### ISSUE THREAD

**Issue by rsluiter** [epics-modules/asyn#2]
When asyn record posts this error message;
"rls2:asyn_9: Error setting option, SIO_BAUD_SET failed: S_errno_EINVAL"
it does not revert the baudrate in either the BAUD or LBAUD fields to a valid value.
Investigate if asyn record can revert the BAUD and/or LBAUD field(s) to the previous, valid value after detecting this error (and also learn how to use github).

**Comment by MarkRivers** [comment]
Fixed.  Did not use Ron's pull request because it is not necessary to change the asynRecord at all.  It is sufficient to have the driver restore the previous value of the baud rate when setting it fails.  Same for all termios settings.
