### ISSUE TITLE
Possible problem with UNIX sockets

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/asyn#31]
I received the following report of a potential problem with Unix sockets.
>Hi, Mark!
>
>My name is Eduardo, I work for the Brazilian Synchrotron Light Laboratory.
>A few days ago, while creating an EPICS IOC with StreamDevice that connects to a UNIX socket, I got some error messages from asynDriver and things didn't work.
>I never studied the asynDriver code in details. But in a quick trial I added two lines of code in the file <asyn_root>/asyn/drvAsynSerial/drvAsynIPPort.c and now everything works and I don't see any error messages. Here is the diff between my modified file (drvAsynIPPort_.c) and the original version (drvAsynIPPort.c):
```
$ diff drvAsynIPPort_.c drvAsynIPPort.c
309,310d308
<         tty->isCom = 0;
<         tty->flags &= ~FLAG_SHUTDOWN;
```
>I'm working with asynDriver 4-30.
>Am I missing something? Or actually is this a bug?
>I put in copy Gustavo, a colleague that is working in the same project.
>Thanks in advance.
>Eduardo

It does look like a bug to me.  In the case of Unix sockets tty->isCom is only ever set to ISCOM_UNKNOWN, and then the test for calling interposeCOM is just for a non-zero value of tty->isCom.

@norumwe12 can you take a look at this?

**Comment by norumwe12** [comment]
Yes, the AF_UNIX side of the conditional in parseHostInfo skips a lot of other processing including changing isCom from ISCOM_UNKNOWN and clearing FLAG_SHUTDOWN.  Perhaps a better fix would be to move these operations outside the AF_UNIX conditional:


[AF_UNIX_patch.txt](https://github.com/epics-modules/asyn/files/569596/AF_UNIX_patch.txt)
