### ISSUE TITLE
Building-problems

### ISSUE THREAD

**Issue by bjoekeldude** [epics-modules/asyn#77]
Trying to "make" asyn on my Beagle Board Black running Debian Stretch, I encounter the following error message, maybe someone has a solution to this:

**debian@beaglebone:~/Apps/epics/modules/asyn$** make
Can't open perl script ".": Is a directory
make -C ./configure install
make[1]: Entering directory '/home/debian/Apps/epics/modules/asyn/configure'
Can't open perl script "..": Is a directory
perl -CSD /home/debian/Apps/epics/modules/asyn/configure/~  /Apps/epics/base/bin/linux-arm/makeMakefile.pl O.linux-arm ../..
Can't open perl script "/home/debian/Apps/epics/modules/asyn/configure/~ /Apps/epics/base/bin/linux-arm/makeMakefile.pl": No such file or directory
/home/debian/Apps/epics/base/configure/RULES_ARCHS:67: recipe for target 'O.linux-arm' failed
make[1]: *** [O.linux-arm] Error 2
make[1]: Leaving directory '/home/debian/Apps/epics/modules/asyn/configure'
/home/debian/Apps/epics/base/configure/RULES_DIRS:84: recipe for target 'configure.install' failed
make: *** [configure.install] Error 2

**Comment by anjohnson** [comment]
You have an error in your configuration settings in configure/RELEASE (or in one of the files it includes). This build line of yours:
```
perl -CSD /home/debian/Apps/epics/modules/asyn/configure/~ /Apps/epics/base/bin/linux-arm/makeMakefile.pl O.linux-arm ../..
```
should look more like this:
```
perl -CSD /home/anj/base-3.15.6/bin/linux-arm/makeMakefile.pl O.linux-arm ../..
```
where the second argument to the `perl` command is the path to a script in the `bin/linux-arm` subdirectory of your EPICS Base installation and the third argument is `O.linux-arm`. In your case it looks like your EPICS_BASE variable has two paths in it.

**Comment by bjoekeldude** [comment]
Thanks for your advise! I'll check this as soon as I have access again to the device.

**Comment by MarkRivers** [comment]
@bjoekeldude has this issue been resolved?

**Comment by MarkRivers** [comment]
I've heard no response in over a month, so I am closing this.
